# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/three_verilog/Uart_ddr3_Hdmi/project_1/project_1.srcs/sources_1/ip/wdata_fifo/wdata_fifo.xci
# IP: The module: 'wdata_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/three_verilog/Uart_ddr3_Hdmi/project_1/project_1.gen/sources_1/ip/wdata_fifo/wdata_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'wdata_fifo'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/three_verilog/Uart_ddr3_Hdmi/project_1/project_1.gen/sources_1/ip/wdata_fifo/wdata_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'wdata_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/three_verilog/Uart_ddr3_Hdmi/project_1/project_1.gen/sources_1/ip/wdata_fifo/wdata_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'wdata_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/three_verilog/Uart_ddr3_Hdmi/project_1/project_1.srcs/sources_1/ip/wdata_fifo/wdata_fifo.xci
# IP: The module: 'wdata_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/three_verilog/Uart_ddr3_Hdmi/project_1/project_1.gen/sources_1/ip/wdata_fifo/wdata_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'wdata_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/three_verilog/Uart_ddr3_Hdmi/project_1/project_1.gen/sources_1/ip/wdata_fifo/wdata_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'wdata_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/three_verilog/Uart_ddr3_Hdmi/project_1/project_1.gen/sources_1/ip/wdata_fifo/wdata_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'wdata_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
